### ISSUE TITLE
numpy' has no attribute 'float

### ISSUE THREAD

**Issue by Inferencer** [csxmli2016/ASFFNet512#8]
```
(net) C:\Users\leolo\ASFFNet512>python main_test.py -s ./TestExamples/TestLists.txt -d ./TestExamples/TestResults
Using device : cpu
Model params : 23.63M
Restoring i1.png
Traceback (most recent call last):
  File "main_test.py", line 159, in <module>
    optimal_ref_landmarks, optimal_ref_path = optimal_reference_selection(lq_landmarks, land_path)
  File "main_test.py", line 80, in optimal_reference_selection
    tmp = [np.float(i) for i in line.split(' ') if i != '\n']
  File "main_test.py", line 80, in <listcomp>
    tmp = [np.float(i) for i in line.split(' ') if i != '\n']
  File "C:\Users\leolo\anaconda3\envs\net\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by Inferencer** [comment]
solved with `pip install "numpy<1.24"`
