### ISSUE TITLE
cuda not enabled with torch

### ISSUE THREAD

**Issue by Inferencer** [csxmli2016/ASFFNet512#9]
getting the following error
```
(net-cuda) C:\Users\leolo\ASFFNet512\TestExamples>python AlignAsFFHQ.py -s ./ObamaRaw -d ./HQReferences/Obama
Traceback (most recent call last):
  File "AlignAsFFHQ.py", line 108, in <module>
    landmarks_detector = face_alignment.FaceAlignment(face_alignment.LandmarksType._3D, flip_input=False)
  File "C:\Users\leolo\anaconda3\envs\net-cuda\lib\site-packages\face_alignment\api.py", line 77, in __init__
    self.face_detector = face_detector_module.FaceDetector(device=device, verbose=verbose, **face_detector_kwargs)
  File "C:\Users\leolo\anaconda3\envs\net-cuda\lib\site-packages\face_alignment\detection\sfd\sfd_detector.py", line 31, in __init__
    self.face_detector.to(device)
  File "C:\Users\leolo\anaconda3\envs\net-cuda\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\leolo\anaconda3\envs\net-cuda\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\leolo\anaconda3\envs\net-cuda\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\leolo\anaconda3\envs\net-cuda\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "C:\Users\leolo\anaconda3\envs\net-cuda\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```
I tried creating and enviroment with this and running
`conda create --name net python=3.8`
and another attempt with 
`conda create --name net-cuda python=3.8 cudatoolkit=11.3`

whats the best way to set up this enviroment on windows, same thing happened with DMDNet but was able to use cpu with that however now would like to be using reference images so came here

**Comment by Inferencer** [comment]
fixed with 
`pip uninstall torch torchaudio torchvision -y`
`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`
and removed cuda visable devices part from inference
